name: tappun-app-studio
slug: tappun-app-studio
description: A gaming-inspired portfolio website showcases mobile apps built with Next.js, TypeScript, and Framer Motion.
description_ja: Next.js、TypeScript、Framer Motion を使用して構築された、モバイルアプリを紹介するゲーム風のポートフォリオウェブサイトです。
translation_locked: false
status: incubating
repo: git@github.com:TakuKobayashi/tappun-app-studio.git
tags:
  - nextjs
  - typescript
  - framer motion
  - portfolio
  - website
  - cloudflare workers
